# --------- #
# latexmkrc #
# --------- #

# Use LuaLaTeX
$lualatex = 'lualatex -interaction=nonstopmode -synctex=1 %O %S';
$pdf_mode = 4;

# Auxiliary files here
$aux_dir = 'out';

# Clean junk
$clean_full_ext = 'acn acr alg aux bbl bcf blg fdb_latexmk fls glg glo gls idx ilg ind ist lof log lot nav out run.xml snm synctex.gz toc xdv';
