# --------- #
# latexmkrc #
# --------- #

# Build
$pdf_mode = 4;               # build PDF
$pdflatex = $lualatex;  # so -pdf uses LuaLaTeX
$lualatex = 'lualatex -interaction=nonstopmode -synctex=1 %O %S';

# Clean
$clean_full_ext = 'acn acr alg aux bbl bcf blg fdb_latexmk fls glg glo gls idx ilg ind ist lof log lot nav out pdf run.xml snm synctex.gz toc xdv';
